name: Hello World

# Trigger the workflow on pull requests targeting the "main" branch
on:
  pull_request:
    branches:
      - main

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello World
        run: echo "Hello, World!"